---
title             : "Predicting intention to receive a seasonal flu vaccine: A Protection Motivation Theory Study"
shorttitle        : "Predicting intention to receive a seasonal flu vaccine"

author: 
  - name          : "Emily J. Kothe"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Deakin University Locked Bag 20000"
    email         : "emily.kothe@deakin.edu.au"
  - name          : "Mathew Ling"
    affiliation   : "1"
  - name          : "Barbara A. Mullan"
    affiliation   : "2"  

affiliation:
  - id            : "1"
    institution   : "Deakin University, Geelong, Australia, Misinformation Lab, School of Psychology"
  - id            : "2"
    institution   : "Health Psychology and Behavioural Medicine Research Group, School of Psychology and Speech Pathology, Curtin University, Perth, Australia"
    
author_note: |
  Emily J. Kothe, Misinformation Lab, School of Psychology, Deakin University, Australia; Mathew Ling, Misinformation Lab, School of Psychology, Deakin University, Australia; Barbara A. Mullan, Health Psychology and Behavioural Medicine Research Group, School of Psychology and Speech Pathology, Curtin University, Perth, Australia.
  
  This research was supported in part by the Deakin University's Health ResAarch Capacity Building Grant ScHeme (HAtCH).  

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
library(knitr)
library(readr)
library(here)
library(dplyr)
library(labelled)
library(tableone)
library(apaTables)
library(stringr)
```

```{r setglobal, cache = FALSE, include = TRUE}

opts_knit$set(root.dir = "..")

options(knitr.kable.NA = '')
```

```{r}
dat <- read_rds(here("data", "dat.rds"))

flu <- dat %>% 
  filter(study=="Flu vaccination")

cont_flu <- flu %>% 
  filter(condition == "Control")
```

```{r demo, results='asis', warning=FALSE}

flu <- flu %>% 
  set_variable_labels(
    age = "Age in years",
    education = "Highest level of education",
    gender = "Gender",
    household_income = "Annual household income", 
    ideology_general = "Ideology - General", 
    ideology_economic = "Ideology - Economic",
    ideology_social = "Ideology - Social")

tab <- CreateTableOne(vars = c("age", 
                             "education",
                             "gender",
                             "household_income", 
                             "ideology_general", 
                             "ideology_economic", 
                             "ideology_social"), 
                    data = flu, test = FALSE)

tab <- print(tab, varLabels = T, printToggle = FALSE)

papaja::apa_table(tab, caption="Demographic characteristics of participants", longtable = TRUE)
```

```{r results="asis"}
corr_tab<-apa.cor.table(select(cont_flu ,flu_int,flu_sev,flu_sus,flu_mrr,flu_se,flu_re,flu_rc),
show.conf.interval = FALSE, landscape = TRUE)

corr_tab<-as.data.frame(corr_tab$table.body)
corr_tab <- corr_tab %>% 
  mutate_all(funs(str_replace(., "\\< \\>", NA_character_))) %>% 
  filter(rowSums(is.na(.)) != ncol(.))
  
apa_table(corr_tab, landscape = TRUE, small=TRUE)
```


```{r results="asis"}


pmt <- lm(flu_int ~ flu_sev + flu_sus + flu_mrr + flu_se + flu_re + flu_rc, data = cont_flu)
pmt_summary <- summary(pmt)
pmt_results <- apa_print(pmt)

apa_table(pmt_results$table, align="lrcrr")
```


# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
